INSERT INTO `db_sensus_penduduk`.`pengguna` (
    `username`,
    `password` 
) VALUES 
('admin', 'admin');

INSERT INTO `db_sensus_penduduk`.`pendidikan` (
    `id`,
    `nama`
) VALUES 
(1, 'Tamat SD/Sederajat'),
(2, 'Tidak/Belum Sekolah'),
(3, 'SLTA/Sederajat'),
(4, 'SLTP/Sederajat'),
(5, 'Belum Tamat SD/Sederajat'),
(6, 'Diploma IV/Strata I'),
(7, 'Diploma I/II'),
(8, 'Akademi/Diploma III/S. Muda'),
(9, 'Strata II'),
(10, 'Strata III');

INSERT INTO `db_sensus_penduduk`.`golongan_darah` (
    `id`,
    `nama`
) VALUES 
(1, 'A'),
(2, 'B'),
(3, 'AB'),
(4, 'O');

INSERT INTO `db_sensus_penduduk`.`penyebab_kematian` (
    `id`,
    `nama`
) VALUES 
(1, 'Sakit Biasa/Usia Tua'),
(2, 'Wabah Penyakit'),
(3, 'Kecalakaan'),
(4, 'Kriminalitas'),
(5, 'Bunuh Diri'),
(6, 'Lainnya');

INSERT INTO `db_sensus_penduduk`.`status_keluarga` (
    `id`,
    `nama`,
    `tingkat`
) VALUES 
(1, 'Kepala Keluarga', 1),
(2, 'Suami', 2),
(3, 'Istri', 3),
(4, 'Anak', 4),
(5, 'Menantu', 5),
(6, 'Cucu', 6),
(7, 'Orang Tua', 7),
(8, 'Mertua', 8),
(9, 'Fimili Lain', 9);

INSERT INTO `db_sensus_penduduk`.`jenis_pekerjaan` (
    `id`,
    `nama`
) VALUES 
(1, 'Belum/Tidak Bekerja'),
(2, 'Mengurus Rumah Tangga'),
(3, 'Pelajar/Mahasiswa'),
(4, 'Pensiun'),
(5, 'Pegawai Negeri Sipil'),
(6, 'Tentara Nasional Indonesia'),
(7, 'Kepolisian RI'),
(8, 'Perdagangan'),
(9, 'Petani/Pekebun'),
(10, 'Peternak'),
(11, 'Nelayan/Perikanan'),
(12, 'Industri'),
(13, 'Konstruksi'),
(14, 'Transportasi'),
(15, 'Karyawan Swasta'),
(16, 'Karyawan BUMN'),
(17, 'Karyawan BUMD'),
(18, 'Karyawan Honorer'),
(19, 'Buruh Harian Lepas'),
(20, 'Buruh Tani/Perkebunan'),
(21, 'Buruh Nelayan/Perikanan'),
(22, 'Buruh Peternakan'),
(23, 'Pembantu Rumah Tangga'),
(24, 'Tukang Cukur'),
(25, 'Tukang Listrik'),
(26, 'Tukang Batu'),
(27, 'Tukang Kayu'),
(28, 'Tukang Sol Sepatu'),
(29, 'Tukang Las/Pandai Besi'),
(30, 'Tukang Jahit'),
(31, 'Penata Rambut'),
(32, 'Penata Rias'),
(33, 'Penata Busana'),
(34, 'Mekanik'),
(35, 'Tukang Gigi'),
(36, 'Seniman'),
(37, 'Tabib'),
(38, 'Paraji'),
(39, 'Perancang Busana'),
(40, 'Penterjemah'),
(41, 'Imam Masjid'),
(42, 'Pendeta'),
(43, 'Pastur'),
(44, 'Wartawan'),
(45, 'Ustadz/Mubaligh'),
(46, 'Juru Masak'),
(47, 'Promotor Acara'),
(48, 'Anggota DPR RI'),
(49, 'Anggota DPD'),
(50, 'Anggota BPK'),
(51, 'Presiden'),
(52, 'Wakit Presiden'),
(53, 'Anggota Mahkaman Konstitusi'),
(54, 'Anggota Kabinet/Kementerian'),
(55, 'Duta Besar'),
(56, 'Gubernur'),
(57, 'Wakil Gubernur'),
(58, 'Bupati'),
(59, 'Wakil Bupati'),
(60, 'Walikota'),
(61, 'Wakil Walikota'),
(62, 'Anggota DPRD Provinsi'),
(63, 'Anggota DPRD Kab/Kota'),
(64, 'Dosen'),
(65, 'Guru'),
(66, 'Pilot'),
(67, 'Pengacara'),
(68, 'Notaris'),
(69, 'Arsitek'),
(70, 'Akuntan'),
(71, 'Konsultan'),
(72, 'Dokter'),
(73, 'Bidan'),
(74, 'Perawat'),
(75, 'Apoteker'),
(76, 'Psikiater/Psikolog'),
(77, 'Penyiar Televisi'),
(78, 'Penyiar Radio'),
(79, 'Peluat'),
(80, 'Peneliti'),
(81, 'Sopir'),
(82, 'Pialang'),
(83, 'Paranormal'),
(84, 'Pedagang'),
(85, 'Perangkat Desa'),
(86, 'Kepala Desa'),
(87, 'Biarawati');

INSERT INTO `db_sensus_penduduk`.`status_perkawinan` (
    `id`,
    `nama`
) VALUES 
(1, 'Belum Kawin'),
(2, 'Kawin'),
(3, 'Cerai Hidup'),
(4, 'Cerai Mati');

INSERT INTO `db_sensus_penduduk`.`agama/kepercayaan` (
    `nama`
) VALUES 
('Islam'),
('Kristen'),
('Katolik'),
('Hindu'),
('Budha'),
('Konghucu');

INSERT INTO `db_sensus_penduduk`.`periode_sensus` (
    `tahun`,
    `tanggal_mulai`,
    `tanggal_selesai`,
    `status` 
) VALUES 
('2010', '2010-01-01', '2011-01-01', 'Menunggu'),
('2015', '2015-01-01', '2016-01-01', 'Menunggu'),
('2020', '2020-01-01', '2021-01-01', 'Berjalan');

INSERT INTO `db_sensus_penduduk`.`kecamatan` (
    `id`,
    `id_periode_sensus`,
    `nama`
) VALUES 
(1, 1, 'Amuntai Selatan'),
(2, 1, 'Amuntai Tengah'),
(3, 1, 'Amuntai Utara'),
(4, 1, 'Babirik'),
(5, 1, 'Banjang'),
(6, 1, 'Danau Panggang'),
(7, 1, 'Haur Gading'),
(8, 1, 'Paminggir'),
(9, 1, 'Sungai Pandan'),
(10, 1, 'Sungai Tabukan'),
(11, 2, 'Amuntai Selatan'),
(12, 2, 'Amuntai Tengah'),
(13, 2, 'Amuntai Utara'),
(14, 2, 'Babirik'),
(15, 2, 'Banjang'),
(16, 2, 'Danau Panggang'),
(17, 2, 'Haur Gading'),
(18, 2, 'Paminggir'),
(19, 2, 'Sungai Pandan'),
(20, 2, 'Sungai Tabukan'),
(21, 3, 'Amuntai Selatan'),
(22, 3, 'Amuntai Tengah'),
(23, 3, 'Amuntai Utara'),
(24, 3, 'Babirik'),
(25, 3, 'Banjang'),
(26, 3, 'Danau Panggang'),
(27, 3, 'Haur Gading'),
(28, 3, 'Paminggir'),
(29, 3, 'Sungai Pandan'),
(30, 3, 'Sungai Tabukan');

INSERT INTO `db_sensus_penduduk`.`kelurahan/desa` (
    `id_kecamatan`,
    `nama`,
    `status`
) VALUES 
(1, 'Bajawit', 'Desa'),
(1, 'Banyu Hirang', 'Desa'),
(1, 'Cangkering', 'Desa'),
(1, 'Cempaka', 'Desa'),
(1, 'Harusan Telaga', 'Desa'),
(1, 'Ilir Mesjid', 'Desa'),
(1, 'Jarang Kuantan', 'Desa'),
(1, 'Jumba', 'Desa'),
(1, 'Kayakah', 'Desa'),
(1, 'Keramat', 'Desa'),
(1, 'Kota Raja', 'Desa'),
(1, 'Kutai Kecil', 'Desa'),
(1, 'Mamar', 'Desa'),
(1, 'Murung Panggang', 'Desa'),
(1, 'Murung Sari', 'Desa'),
(1, 'Padang Darat', 'Desa'),
(1, 'Padang Tanggul', 'Desa'),
(1, 'Penyiuran', 'Desa'),
(1, 'Pulau Tambak', 'Desa'),
(1, 'Rukam Hilir', 'Desa'),
(1, 'Rukam Hulu', 'Desa'),
(1, 'Simpang Empat', 'Desa'),
(1, 'Simpang Tiga', 'Desa'),
(1, 'Telaga Hanyar', 'Desa'),
(1, 'Telaga Sari', 'Desa'),
(1, 'Telaga Silaba', 'Desa'),
(1, 'Teluk Baru', 'Desa'),
(1, 'Teluk Paring', 'Desa'),
(1, 'Teluk Sari', 'Desa'),
(2, 'Danau Ceramin', 'Desa'),
(2, 'Datu Kuning', 'Desa'),
(2, 'Harus', 'Desa'),
(2, 'Harusan', 'Desa'),
(2, 'Hulu Pasar', 'Desa'),
(2, 'Kandang Halang', 'Desa'),
(2, 'Kembang Kuning', 'Desa'),
(2, 'Kota Raden Hilir', 'Desa'),
(2, 'Kota Raden Hulu', 'Desa'),
(2, 'Mawar Sari', 'Desa'),
(2, 'Muara Tapus', 'Desa'),
(2, 'Palampitan Hilir', 'Desa'),
(2, 'Palampitan Hulu', 'Desa'),
(2, 'Pasar Senin', 'Desa'),
(2, 'Pinang Habang', 'Desa'),
(2, 'Pinang Kara', 'Desa'),
(2, 'Rantawan', 'Desa'),
(2, 'Sungai Baring', 'Desa'),
(2, 'Sungai Karias', 'Desa'),
(2, 'Tambalangan', 'Desa'),
(2, 'Tangga Ulin Hilir', 'Desa'),
(2, 'Tangga Ulin Hulu', 'Desa'),
(2, 'Tapus', 'Desa'),
(2, 'Tigarun', 'Desa'),
(2, 'Antasari', 'Kelurahan'),
(2, 'Kebun Sari', 'Kelurahan'),
(2, 'Murung Sari', 'Kelurahan'),
(2, 'Paliwara', 'Kelurahan'),
(2, 'Sungai Malang', 'Kelurahan'),
(3, 'Air Tawar', 'Desa'),
(3, 'Cakru', 'Desa'),
(3, 'Guntung', 'Desa'),
(3, 'Kamayahan', 'Desa'),
(3, 'Kuangan', 'Desa'),
(3, 'Muara Baruh', 'Desa'),
(3, 'Murung Karangan', 'Desa'),
(3, 'Padang Basar', 'Desa'),
(3, 'Padang Basar Hilir', 'Desa'),
(3, 'Padang Luar', 'Desa'),
(3, 'Pakacangan', 'Desa'),
(3, 'Pakapuran', 'Desa'),
(3, 'Pamintangan', 'Desa'),
(3, 'Panangian', 'Desa'),
(3, 'Panangkalaan', 'Desa'),
(3, 'Panangkalaan Hulu', 'Desa'),
(3, 'Pandawanan', 'Desa'),
(3, 'Panyaungan', 'Desa'),
(3, 'Pimping', 'Desa'),
(3, 'Sungai Turak', 'Desa'),
(3, 'Sungai Turak Dalam', 'Desa'),
(3, 'Tabalong Mati', 'Desa'),
(3, 'Tabing Liring', 'Desa'),
(3, 'Tayur', 'Desa'),
(3, 'Telaga Bamban', 'Desa'),
(3, 'Teluk Daun', 'Desa'),
(11, 'Ujung Murung', 'Desa'),
(11, 'Bajawit', 'Desa'),
(11, 'Banyu Hirang', 'Desa'),
(11, 'Cangkering', 'Desa'),
(11, 'Cempaka', 'Desa'),
(11, 'Harusan Telaga', 'Desa'),
(11, 'Ilir Mesjid', 'Desa'),
(11, 'Jarang Kuantan', 'Desa'),
(11, 'Jumba', 'Desa'),
(11, 'Kayakah', 'Desa'),
(11, 'Keramat', 'Desa'),
(11, 'Kota Raja', 'Desa'),
(11, 'Kutai Kecil', 'Desa'),
(11, 'Mamar', 'Desa'),
(11, 'Murung Panggang', 'Desa'),
(11, 'Murung Sari', 'Desa'),
(11, 'Padang Darat', 'Desa'),
(11, 'Padang Tanggul', 'Desa'),
(11, 'Penyiuran', 'Desa'),
(11, 'Pulau Tambak', 'Desa'),
(11, 'Rukam Hilir', 'Desa'),
(11, 'Rukam Hulu', 'Desa'),
(11, 'Simpang Empat', 'Desa'),
(11, 'Simpang Tiga', 'Desa'),
(11, 'Telaga Hanyar', 'Desa'),
(11, 'Telaga Sari', 'Desa'),
(11, 'Telaga Silaba', 'Desa'),
(11, 'Teluk Baru', 'Desa'),
(11, 'Teluk Paring', 'Desa'),
(11, 'Teluk Sari', 'Desa'),
(11, 'Ujung Murung', 'Desa'),
(21, 'Bajawit', 'Desa'),
(21, 'Banyu Hirang', 'Desa'),
(21, 'Cangkering', 'Desa'),
(21, 'Cempaka', 'Desa'),
(21, 'Harusan Telaga', 'Desa'),
(21, 'Ilir Mesjid', 'Desa'),
(21, 'Jarang Kuantan', 'Desa'),
(21, 'Jumba', 'Desa'),
(21, 'Kayakah', 'Desa'),
(21, 'Keramat', 'Desa'),
(21, 'Kota Raja', 'Desa'),
(21, 'Kutai Kecil', 'Desa'),
(21, 'Mamar', 'Desa'),
(21, 'Murung Panggang', 'Desa'),
(21, 'Murung Sari', 'Desa'),
(21, 'Padang Darat', 'Desa'),
(21, 'Padang Tanggul', 'Desa'),
(21, 'Penyiuran', 'Desa'),
(21, 'Pulau Tambak', 'Desa'),
(21, 'Rukam Hilir', 'Desa'),
(21, 'Rukam Hulu', 'Desa'),
(21, 'Simpang Empat', 'Desa'),
(21, 'Simpang Tiga', 'Desa'),
(21, 'Telaga Hanyar', 'Desa'),
(21, 'Telaga Sari', 'Desa'),
(21, 'Telaga Silaba', 'Desa'),
(21, 'Teluk Baru', 'Desa'),
(21, 'Teluk Paring', 'Desa'),
(21, 'Teluk Sari', 'Desa'),
(21, 'Ujung Murung', 'Desa');

INSERT INTO `db_sensus_penduduk`.`pegawai` (
    `id`,
    `id_pendidikan`,
    `id_agama/kepercayaan`,
    `nip`,
    `nama`,
    `tempat_lahir`,
    `tanggal_lahir`,
    `foto` 
) VALUES 
(1, 6, 1, '199610102019022001', 'Ida Faridatul Alawiyah, S.ST', 'Binuang', '1996-10-10', ''),
(2, 6, 1, '198609262015051002', 'Awanis, S.TP., M.Si', 'Binuang', '1995-01-01', ''),
(3, 6, 1, '198609262015051007', 'Muhammad Ali', 'Binuang', '1986-09-26', ''),
(4, 6, 1, '198609262015051003', 'Muhammad Syarif, S.ST', 'Binuang', '1995-01-01', ''),
(5, 6, 1, '198609262015051331', 'Puspita Harum Maharani, M.Sc', 'Binuang', '1995-01-01', ''),
(6, 6, 1, '198609262115051331', 'Ahmad Isa Anshari, SE', 'Martapura', '1995-01-01', ''),
(7, 6, 1, '198609262115051332', 'Ade Hasan Basri', 'Banjarbaru', '1995-01-01', ''),
(8, 6, 1, '198609262115051333', 'Akli', 'Banjarmasin', '1995-01-01', ''),
(9, 6, 1, '198609262115051334', 'Alfianoor', 'Semarang', '1995-01-01', ''),
(10, 6, 1, '198609262115051335', 'Ariadi, S.Pi', 'Bandung', '1995-01-01', ''),
(11, 6, 1, '198609262115051336', 'Bachtiar', 'Martapura', '1995-01-01', ''),
(12, 6, 1, '198609262115051337', 'Jumarni', 'Martapura', '1995-01-01', ''),
(13, 6, 1, '198609262115051338', 'Kusyanti', 'Martapura', '1995-01-01', ''),
(14, 6, 1, '198609262115051339', 'Gusti Maisarah', 'Martapura', '1995-01-01', ''),
(15, 6, 1, '198609262115051340', 'Agus Setiati', 'Martapura', '1995-01-01', ''),
(16, 6, 1, '198609262115051341', 'Fiqy Hilmawan, S.Pt., M.Si', 'Martapura', '1995-01-01', ''),
(17, 6, 1, '198619262115051341', 'Firmansyah, S.AP"', 'Martapura', '1995-01-01', ''),
(18, 6, 1, '198609262115051342', 'Juhdy', 'Martapura', '1995-01-01', ''),
(19, 6, 1, '198609262115051344', 'Kamaruddin', 'Martapura', '1995-01-01', ''),
(20, 6, 1, '198609262115051346', 'Masdar', 'Martapura', '1995-01-01', ''),
(21, 6, 1, '198609262115051347', 'Pagiyanto, S.ST', 'Martapura', '1995-01-01', ''),
(22, 6, 1, '198609262115051348', 'Sumari', 'Martapura', '1995-01-01', ''),
(23, 6, 1, '198609262115051349', 'Suradi', 'Martapura', '1995-01-01', ''),
(24, 6, 1, '198609262115051350', 'Puspita Harum Maharani, SP., M.Sc', 'Martapura', '1995-01-01', ''),
(25, 6, 1, '198609262115051351', 'Rasunawaty', 'Martapura', '1995-01-01', ''),
(26, 6, 1, '198609262115051352', 'Rudy Ariani', 'Martapura', '1995-01-01', ''),
(27, 6, 1, '198609262115051353', 'Shinta Anggreany, M.Si', 'Martapura', '1995-01-01', ''),
(28, 6, 1, '198609262115051354', 'Sudiyono', 'Martapura', '1995-01-01', ''),
(29, 6, 1, '198609262115051355', 'Sumadi', 'Martapura', '1995-01-01', ''),
(30, 6, 1, '198609262115051356', 'Fungsional Umum', 'Martapura', '1995-01-01', '');

INSERT INTO `db_sensus_penduduk`.`penduduk` (
    `id`,
    `id_kelurahan/desa`,
    `id_golongan_darah`,
    `id_pendidikan`,
    `id_jenis_pekerjaan`,
    `id_status_perkawinan`,
    `id_agama/kepercayaan`,
    `id_periode_sensus`,
    `nik`,
    `nama`,
    `tempat_lahir`,
    `tanggal_lahir`,
    `jenis_kelamin`,
    `nik_ibu_kandung`,
    `nama_ibu_kandung`,
    `nik_ayah_kandung`,
    `nama_ayah_kandung`,
    `alamat_sebelumnya`,
    `alamat_sekarang` 
) VALUES 
(1, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(2, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(3, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(4, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(5, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(6, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(7, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(8, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(9, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(10, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(11, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(12, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(13, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(14, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(15, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(16, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(17, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(18, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(19, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(20, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(21, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(22, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(23, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(24, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(25, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(26, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(27, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(28, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(29, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(30, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(31, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(32, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(33, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(34, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(35, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(36, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(37, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(38, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(39, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(40, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(41, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(42, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(43, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(44, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(45, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(46, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(47, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(48, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(49, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(50, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(51, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(52, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(53, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(54, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(55, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(56, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(57, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(58, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(59, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(60, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(61, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(62, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(63, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(64, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(65, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(66, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(67, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(68, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(69, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(70, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(71, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(72, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(73, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(74, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(75, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(76, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(77, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(78, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(79, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(80, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(81, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(82, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(83, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(84, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(85, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(86, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(87, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(88, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(89, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(90, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(91, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(92, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(93, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(94, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(95, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(96, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(97, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(98, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(99, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(100, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(101, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(102, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(103, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(104, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(105, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(106, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(107, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(108, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(109, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(110, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(111, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(112, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(113, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(114, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(115, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(116, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(117, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(118, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(119, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(120, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(121, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(122, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(123, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(124, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(125, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(126, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(127, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(128, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(129, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(130, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(131, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(132, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(133, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(134, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(135, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(136, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(137, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(138, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(139, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(140, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(141, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(142, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(143, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(144, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(145, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(146, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(147, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(148, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(149, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(150, 1, 1, 1, 1, 1, 1, 1, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(151, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(152, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(153, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(154, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(155, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(156, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(157, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(158, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(159, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(160, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(161, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(162, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(163, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(164, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(165, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(166, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(167, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(168, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(169, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(170, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(171, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(172, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(173, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(174, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(175, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(176, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(177, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(178, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(179, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(180, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(181, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(182, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(183, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(184, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(185, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(186, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(187, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(188, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(189, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(190, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(191, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(192, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(193, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(194, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(195, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(196, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(197, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(198, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(199, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(200, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(201, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(202, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(203, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(204, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(205, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(206, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(207, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(208, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(209, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(210, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(211, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(212, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(213, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(214, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(215, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(216, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(217, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(218, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(219, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(220, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(221, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(222, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(223, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(224, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(225, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(226, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(227, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(228, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(229, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(230, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(231, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(232, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(233, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(234, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(235, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(236, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(237, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(238, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(239, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(240, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(241, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(242, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(243, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(244, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(245, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(246, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(247, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(248, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(249, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(250, 1, 1, 1, 1, 1, 1, 2, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(251, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(252, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(253, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(254, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(255, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(256, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(257, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(258, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(259, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(260, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(261, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(262, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(263, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(264, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(265, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(266, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(267, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(268, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(269, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(270, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(271, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(272, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(273, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(274, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(275, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(276, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(277, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(278, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(279, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(280, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(281, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(282, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(283, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(284, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(285, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(286, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(287, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(288, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(289, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(290, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(291, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(292, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(293, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(294, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(295, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(296, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(297, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(298, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(299, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang'),
(300, 1, 1, 1, 1, 1, 1, 3, 'nik', 'nama', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin', 'nik_ibu_kandung', 'nama_ibu_kandung', 'nik_ayah_kandung', 'nama_ayah_kandung', 'alamat_sebelumnya', 'alamat_sekarang');